### ISSUE TITLE
Dual Wield issue.

### ISSUE THREAD

**Issue by Lakefruit** [Ciastex/ArcadeCoinBugCentral#67] opened 2020-01-25 21:53 UTC
#### Variables when discovered
- Endless mode
- Duelist Card
- Wave 6
- Dual wielding weapons
    - Revolver in left hand
    - Magnum in right hand

#### Expected behavior
Ability to pause and unpause while dual wielding without having to unequip and reequip your second weapon.
   
#### Actual behavior
I paused and unpaused the game; upon unpausing, I noted that clicking RMB did not fire my magnum. I clicked LMB, and both weapons fired simultaneously.

#### Steps to reproduce
1. I fixed the issue by pressing Q again (canceling the dual wielding)
2. Then pressing Q again to reactivate dual wielding.
[I was able to reproduce the bug multiple times with the same variables as listed above.]

**Comment by TieDyeTopHat** [comment] 2020-01-25 21:58
Duplicate of #30

**Closed by TieDyeTopHat** 2020-01-25 21:58 UTC
