### ISSUE TITLE
Looking behind you

### ISSUE THREAD

**Issue by HereticYT** [Ciastex/ArcadeCoinBugCentral#58] opened 2020-01-09 06:22 UTC
#### Expected behavior
Not to be able to look behind you from looking down when jumping
   
#### Actual behavior
Able to look behind you from looking down when jumping
  
#### Steps to reproduce
1. Jump and look down
 
#### Additional information
Looks kinda funny because you can do back flips and front flips, now I'm not so sure if this is in the base game itself, but I figured this out from my experience in the Demo.

**Comment by silent93x** [comment] 2020-01-09 11:43
This is an intended feature, close it!

**Comment by silent93x** [comment] 2020-01-09 11:44
It's not a bug!

**Closed** 2020-01-10 21:22 UTC
